project_name: mixer-server
before:
  hooks:
    - go mod tidy
builds:
  - env:
    - CGO_ENABLED=0
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64
  main: ./cmd/mixer-server
  binary: mixer-server
archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*
changelog:
  filters:
    exclude:
      - '^Merge pull request #'